name: v3ladder Docker image arm64

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/arm64.yaml'
      - 'docker/Dockerfile'

jobs:
  build-docker-image-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.4'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: v3ladder-image

      - name: Build Go project Linux arm64
        run: |
          cd v3ladder-image
          go env -w GOPRIVATE="github.com/HaoweiCh/*,github.com/haoweich/*"
          git config --global url."https://oauth:${{ secrets.PAT }}@github.com/HaoweiCh/".insteadOf "https://github.com/HaoweiCh/"
          git config --global url."https://oauth:${{ secrets.PAT }}@github.com/HaoweiCh/".insteadOf "https://github.com/haoweich/"
          go mod tidy
          GOARCH=arm64 GOOS=linux CGO_ENABLED=0 go build --trimpath -ldflags '-s -w' -o docker/app ./v3ladder/main.go

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: v3ladder-image/docker
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/v3ladder:arm64
          platforms: linux/arm64
